### PR TITLE
use sandbox to clean up stubs after each test

### PR DESCRIPTION
**Pull request by leggsimon**
@debugwand I think this was the one you mentioned earlier

### CODE REVIEW

**Comment by debugwand** [comment]
see https://github.com/Financial-Times/next-myft-page/blob/master/test/server/controllers/v2/alerts/unsubscribe-via-get.spec.js and http://sinonjs.org/releases/v2.0.0/sandbox/

stubs need to be created in beforeEach

**Comment by leggsimon** [comment]
Does this matter since the stubs were being set up in each test anyway?

I have just refactored the repeated stubs to be shared between tests, setting up and restoring each of them before and after respectively. But I think this is more just a tidying up rather than whether it was actually necessary?

**Comment by debugwand** [comment]
the cod tidy-up is fine, the comment was to point to how we work with restore not resetting stubs, as per our discussion yesterday

**Comment by leggsimon** [comment]
Yep I realised after I wrote that comment that it was much more pertinent to the changes I've just made in `digest.spec.js` as that had stubs that were being set up once and being shared amongst all the individual tests.

**Pull request merged**
