### PR TITLE
Add link to sponsorship image

### PR DESCRIPTION
**Pull request by keirog**

### CODE REVIEW

**Comment by laurieboyes** [comment]
👍

**Comment by leggsimon** [comment]
@adgad Is suggesting we add `data-trackable`s to the link FYI. (I'm using `myft-sponsorship:frontpage`)

**Comment by keirog** [comment]
@leggsimon Aye, there’s already one in this PR :-p
Am happy to rename to `myft-sponsorship`. Btw you don‘t need the `:frontpage` bit as the `<body>` already has `data-trackable="page:front-page"`

**Comment by leggsimon** [comment]
Oh sorry I looked but obviously didn't see it

**Pull request merged**
