### PR TITLE
Hopefully reduce graphql-api timeout errors

### PR DESCRIPTION
**Pull request by keirog**
The default is 4 secs; have changed to 10 secs

### CODE REVIEW

**Comment by laurieboyes** [comment]
👍

**Comment by phamann** [comment]
I'm afraid this won't have any effect, both Fastly and our router have a hard cut off of 3 secs. Therefore the connection will be closed before this can finish.

**Comment by keirog** [comment]
Oh, damn ok ta

**Comment by phamann** [comment]
The solution is to fix the underlying slowness of the service graph-ql is hitting, not just up the timeout 😺

**Comment by ironsidevsquincy** [comment]
The graphql api isn't behind fastly, but yeah, the router timeout will kick in

**Comment by keirog** [comment]
I thought it wouldn't do any harm as it's polling, but didn't realised about the router timeout. Drat

**Pull request merged**
