### PR TITLE
Use createReleationship instead of update for layout-switching

### PR DESCRIPTION
**Pull request by phamann**
/cc @Financial-Times/next-myft

### CODE REVIEW

**Comment by adgad** [comment]
Isn't it `addRelationship`?

**Comment by adgad** [comment]
Also `addRelationship`'s body is the node e.g. 
```
{ uuid: 'myft-layout' }
```

Not sure if we ever got round to adding support for this in the API, but you'd need to do something like:
```
{ 
uuid: 'myft-layout',
_rel: {
layout: 'grouped'
 }
```

**Comment by phamann** [comment]
@adgad Good catch :wink: seems that the terminology in the `crud.js` does not match the client.

**Comment by phamann** [comment]
@adgad Yep we do support `_rel` https://github.com/Financial-Times/next-myft-api/blob/master/server/v1/models/crud.js#L277-L291

**Pull request merged**
