### PR TITLE
Path has-bin (sorry)

### PR DESCRIPTION
**Pull request by keirog**

### CODE REVIEW

**Comment by phamann** [comment]
:+1: Based on recent findings we would even consider ditching `forever` entirely?

**Comment by phamann** [comment]
Heroku Dyno crash restart policy: https://devcenter.heroku.com/articles/dynos#dyno-crash-restart-policy

**Comment by keirog** [comment]
"After the 320 minute cool-off period is reached, restart attempts happen every 320 minutes"

**Comment by keirog** [comment]
I'll merge this in and we can decide about forever later.

Forever later™

**Pull request merged**
